var ols=[
{caption:"المقدمة",page:"1",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار اليوم والليلة</span>",page:"4",url:"",level:"1",children:[]},
{caption:"دُعَاءُ الاسْتِيقَاظِ مِنَ النَّوْمِ",page:"4",url:"",level:"1",children:[]},
{caption:"دُعَاءُ بَعْدَ الوُضُوءِ",page:"8",url:"",level:"1",children:[]},
{caption:"وَيَفْتَتِحُ التَّهَجُدَ",page:"8",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار آخر الليل بعد ختم الوتر</span>",page:"11",url:"",level:"1",children:[]},
{caption:"الدُّعَاءُ بِأَسْمَاءِ اللَّهِ الحُسْنَى",page:"12",url:"",level:"1",children:[]},
{caption:"قَصِيْدَةُ الإِمَامِ العَدني ( إلهي نسألك)",page:"19",url:"",level:"1",children:[]},
{caption:"قَصِيدَةُ الإِمَامِ الحَدَّاد (يا ربّ يا عالم الحال)",page:"21",url:"",level:"1",children:[]},
{caption:"قَصِيدَةُ (يا أرحم الراحمين)",page:"24",url:"",level:"1",children:[]},
{caption:"قَصِيدَةُ الحَبِيبِ عَلِيِّ الحَبَشِي (ربي إني )",page:"26",url:"",level:"1",children:[]},
{caption:"قَصِيدَةُ الإِمَامِ الحَدَّاد (قد كفاني علم ربي)",page:"27",url:"",level:"1",children:[]},
{caption:"دَعَوَاتٌ للحَبِيبِ مُحَمَّد الهَدَّار (فقل معي)",page:"29",url:"",level:"1",children:[]},
{caption:"وِرْدُ سَيِّدِنَا الشَّيْخِ أَبِي بَكْر بن سَالِم",page:"32",url:"",level:"1",children:[]},
{caption:"دعاء الخروج مِنَ البيت",page:"36",url:"",level:"1",children:[]},
{caption:"دُعَاءُ المَشْي إِلَى المَسْجِد وإِلَى كُلِّ طَاعَة",page:"36",url:"",level:"1",children:[]},
{caption:"دُعَاءُ الدُّخُولِ إِلَى المَسْجِد",page:"37",url:"",level:"1",children:[]},
{caption:"دُعَاءُ الخروج مِنَ المَسْجِد",page:"37",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما قبل الفجر</span>",page:"38",url:"",level:"1",children:[]},
{caption:"دعاء الفجر",page:"38",url:"",level:"1",children:[]},
{caption:"الذِّكْر قَبْلَ إقَامَةِ الصَّلَاةِ",page:"42",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد الصلاة</span>",page:"43",url:"",level:"1",children:[]},
{caption:"دعاء المسلمين",page:"48",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد صلاة الفجر</span>",page:"51",url:"",level:"1",children:[]},
{caption:"الوِرْدُ اللَّطِيفُ لِلإِمَامِ الحَدَّادِ",page:"55",url:"",level:"1",children:[]},
{caption:"سورة يس",page:"64",url:"",level:"1",children:[]},
{caption:"الدُّعَاءُ بعد يس",page:"70",url:"",level:"1",children:[]},
{caption:"ورد الإمامِ أَبِي بَكْرِ بنِ عَبْدِ الرَّحْمَنِ السَّقَّافِ",page:"72",url:"",level:"1",children:[]},
{caption:"وِرْدُ الإِمَامِ النَّوَوِي",page:"75",url:"",level:"1",children:[]},
{caption:"دُعَاء بَعْدَ صَلاةِ الضُّحَى",page:"81",url:"",level:"1",children:[]},
{caption:"دُعَاءُ الاسْتِخَارَة",page:"84",url:"",level:"1",children:[]},
{caption:"نيَّاتُ التَّعَلُّمِ وَالتَّعْلِيم للإمام الحدَّاد",page:"86",url:"",level:"1",children:[]},
{caption:"دُعاءُ الإِخْوَانِ في اللَّهِ",page:"86",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد الظهر</span>",page:"90",url:"",level:"1",children:[]},
{caption:"حِزْبُ النَّصْرِ للإِمَامِ الحَدَّاد",page:"90",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد العصر</span>",page:"95",url:"",level:"1",children:[]},
{caption:"سُورَةُ الوَاقِعَة",page:"95",url:"",level:"1",children:[]},
{caption:"الدُّعَاءُ الَّذِي يُقْرَأُ بَعْدَ سُورَةِ الوَاقِعَة",page:"99",url:"",level:"1",children:[]},
{caption:"حزب البَحْرِ لِسَيدِي أَبي الحَسَن الشَّاذِلِي",page:"101",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما قبل المغرب وما بعده</span>",page:"108",url:"",level:"1",children:[]},
{caption:"رَاتِبُ الإِمَامِ عُمَرِ بنِ عَبْدِ الرَّحْمَنِ العَطَّاسِ",page:"109",url:"",level:"1",children:[]},
{caption:"رَاتِبُ الإِمَامِ عَبْدِ اللّهِ بِنْ عَلْوِي الْحَدَّادِ",page:"118",url:"",level:"1",children:[]},
{caption:"العقيدة للإمام علي بن أبي بَكْر السَّكران",page:"126",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد العشاء</span>",page:"129",url:"",level:"1",children:[]},
{caption:"سورة السجدة",page:"130",url:"",level:"1",children:[]},
{caption:"سورة الملك",page:"133",url:"",level:"1",children:[]},
{caption:"دُعَاء سَجْدَتَيِ التِّلَاوَة والشكر",page:"136",url:"",level:"1",children:[]},
{caption:"دُعَاءُ النَّوْمِ",page:"137",url:"",level:"1",children:[]},
{caption:"دُعَاءُ صَلاةِ التَّسْبِيح",page:"140",url:"",level:"1",children:[]},
{caption:"دُعَاءُ السَّفَر",page:"141",url:"",level:"1",children:[]},
{caption:"إِذَا هَمَّ بِالخُرُوجِ مِن بَابِ دَارِهِ",page:"142",url:"",level:"1",children:[]},
{caption:"وَمِنَ المجَرَّبِ للحِفْظِ عِنْدَ الخُرُوج",page:"143",url:"",level:"1",children:[]},
{caption:"فَإِذَا مَشَى قَالَ",page:"143",url:"",level:"1",children:[]},
{caption:"فَإِذَا رَكِبَ يَقُول",page:"144",url:"",level:"1",children:[]},
{caption:"فَإِذَا اسْتَوَى عَلَى مَرْكُوبِهِ قَالَ",page:"145",url:"",level:"1",children:[]},
{caption:"يَزِيدُ رَاكِبُ السَّيَّارَةِ أَوِ الطَّائِرَةِ أَوِ البَاخِرَةِ ",page:"145",url:"",level:"1",children:[]},
{caption:"دُعَاءٌ عَنْ أَمِيرِ الْمُؤْمِنِينَ عَلِيٍّ عَلَيْهِ السَّلام",page:"146",url:"",level:"1",children:[]},
{caption:"دُعَاءِ الكَرْبِ",page:"147",url:"",level:"1",children:[]},
{caption:"فَإِذَا خَافَ أَحَدًا",page:"148",url:"",level:"1",children:[]},
{caption:"وإِذَا عَلا شَرفاً مِنَ الْأَرْضِ",page:"149",url:"",level:"1",children:[]},
{caption:"وَإِذَا خَافَ الوَحْشَةَ",page:"149",url:"",level:"1",children:[]},
{caption:"فَإِذَا جَنَّ عَلَيْهِ اللَّيْل",page:"149",url:"",level:"1",children:[]},
{caption:"وَإِذَا أَشْرَفَ عَلَى بَلَدِهِ أَوْ غَيْرِهِ",page:"150",url:"",level:"1",children:[]},
{caption:"دُعَاءُ دُخُولِ المَنْزِل",page:"151",url:"",level:"1",children:[]},
{caption:"ما ينبغي الإكثار منه عند النوازل والشدائد",page:"153",url:"",level:"1",children:[]},
{caption:"<span id='utama'>منظومة المشرب الأهني</span>",page:"158",url:"",level:"1",children:[]},
{caption:"خَاتِمَةُ القَصِيدَةِ التَّائِيَّةِ لِلإِمَامِ الحَدَّادِ",page:"160",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ليلة الجمعة ويومها</span>",page:"162",url:"",level:"1",children:[]},
{caption:"سورة الكهف",page:"165",url:"",level:"1",children:[]},
{caption:"سورة الدخان",page:"177",url:"",level:"1",children:[]},
{caption:"سورة المزمل",page:"180",url:"",level:"1",children:[]},
{caption:"سورة البروج",page:"182",url:"",level:"1",children:[]},
{caption:"سورة الطارق",page:"183",url:"",level:"1",children:[]},
{caption:"الصَّلاةُ الإِبْرَاهِيمِيَّة",page:"188",url:"",level:"1",children:[]},
{caption:"الصَّلاةُ التَّاجِيَّةُ لِلشَّيْخِ أَبِي بَكْر بن سَالِم",page:"190",url:"",level:"1",children:[]},
{caption:"قَصِيدَةَ (يا ربنا أنت لنا كهف وغوث)",page:"193",url:"",level:"1",children:[]},
{caption:"<span id='utama'>أذكار ما بعد عصر الجمعة</span>",page:"195",url:"",level:"1",children:[]},
{caption:"<span id='utama'>بعض صيغ الصلاة على النبي صلى الله عليه وسلم</span>",page:"197",url:"",level:"1",children:[]},
{caption:"دُعَاءٌ يُقَالُ فِي خِتَامِ الْمَجَالِسِ وَالدُّرُوس",page:"203",url:"",level:"1",children:[]}
];