var ols=[
{caption:"خطبة الكتاب",page:"1",url:"",level:"1",children:[]},
{caption:"الفصاحة - البلاغة - الأسلوب",page:"2",url:"",level:"1",children:[]},
{caption:"علم البيان - التشبيه - أركانه",page:"15",url:"",level:"1",children:[]},
{caption:"أقسامه",page:"20",url:"",level:"1",children:[]},
{caption:"أغراضه",page:"49",url:"",level:"1",children:[]},
{caption:"بلاغته وبعض ما أثر منه عن العرب والمحدثين",page:"62",url:"",level:"1",children:[]},
{caption:"الحقيقة والمجاز - المجاز اللغوي",page:"66",url:"",level:"1",children:[]},
{caption:"الاستعارة التصريحية والمكنية",page:"72",url:"",level:"1",children:[]},
{caption:"تقسيم الاستعارة إلى تبعية وأصلية",page:"79",url:"",level:"1",children:[]},
{caption:"تقسيم الاستعارة إلى مرشحة ومجردة ومطلقة",page:"86",url:"",level:"1",children:[]},
{caption:"الاستعارة التمثيلية",page:"94",url:"",level:"1",children:[]},
{caption:"بلاغة الاستعارة وشواهد ذلك من المنظوم والمنثور",page:"102",url:"",level:"1",children:[]},
{caption:"المجاز المرسل وعلاقاته",page:"105",url:"",level:"1",children:[]},
{caption:"المجاز العقلي",page:"112",url:"",level:"1",children:[]},
{caption:"الكناية وأقسامها",page:"120",url:"",level:"1",children:[]},
{caption:"بلاغة الكناية وشواهد ذلك من الكلام البليغ",page:"128",url:"",level:"1",children:[]},
{caption:"أثر علم البيان في تأدية المعاني",page:"130",url:"",level:"1",children:[]},
{caption:"علم المعاني - تقسيم الكلام إلى خبر وإنشاء",page:"134",url:"",level:"1",children:[]},
{caption:"الخبر - الغرض من إلقائه",page:"141",url:"",level:"1",children:[]},
{caption:"أضربه",page:"150",url:"",level:"1",children:[]},
{caption:"خروجه عن مقتضى الظاهر",page:"159",url:"",level:"1",children:[]},
{caption:"الإنشاء وتقسيمه إلى طلبي وغير طلبي",page:"164",url:"",level:"1",children:[]},
{caption:"الإنشاء الطلبي وأقسامه - الأمر",page:"173",url:"",level:"1",children:[]},
{caption:"النهي",page:"181",url:"",level:"1",children:[]},
{caption:"الاستفهام",page:"189",url:"",level:"1",children:[]},
{caption:"التمني",page:"203",url:"",level:"1",children:[]},
{caption:"النداء",page:"207",url:"",level:"1",children:[]},
{caption:"القصر",page:"213",url:"",level:"1",children:[]},
{caption:"الفصل والوصل",page:"224",url:"",level:"1",children:[]},
{caption:"الإيجاز والإطناب والمساواة",page:"236",url:"",level:"1",children:[]},
{caption:"أثر علم المعاني في بلاغة الكلام",page:"255",url:"",level:"1",children:[]},
{caption:"علم البديع - أثره في الكلام وتقسيمه - المحسنات اللفظية - الجناس",page:"260",url:"",level:"1",children:[]},
{caption:"الاقتباس",page:"266",url:"",level:"1",children:[]},
{caption:"السجع",page:"269",url:"",level:"1",children:[]},
{caption:"المحسنات المعنوية - التورية",page:"273",url:"",level:"1",children:[]},
{caption:"الطباق",page:"277",url:"",level:"1",children:[]},
{caption:"المقابلة",page:"281",url:"",level:"1",children:[]},
{caption:"حسن التعليل",page:"285",url:"",level:"1",children:[]},
{caption:"تأكيد المدح بما يشبه الذم وعكسه",page:"288",url:"",level:"1",children:[]},
{caption:"أسلوب الحكيم",page:"292",url:"",level:"1",children:[]}
];