var ols=[
{caption:"أركان الإسلام",page:"1",url:"",level:"1",children:[]},
{caption:"فروض الوضوء",page:"2",url:"",level:"1",children:[]},
{caption:"شروط الوضوء",page:"4",url:"",level:"1",children:[]},
{caption:"دعاء ما بعد الوضوء",page:"4",url:"",level:"1",children:[]},
{caption:"أركان الصلاة",page:"6",url:"",level:"1",children:[]},
{caption:"شروط الصلاة",page:"7",url:"",level:"1",children:[]},
{caption:"دعاء الافتتاح",page:"8",url:"",level:"1",children:[]},
{caption:"دعاء الاعتدال",page:"10",url:"",level:"1",children:[]},
{caption:"دعاء الجلوس بين السجدتين",page:"11",url:"",level:"1",children:[]},
{caption:"التشهد",page:"11",url:"",level:"1",children:[]},
{caption:"الصلاة الإبراهيمية",page:"12",url:"",level:"1",children:[]},
{caption:"دعاء التشهد الأخير",page:"13",url:"",level:"1",children:[]},
{caption:"القنوت",page:"15",url:"",level:"1",children:[]},
{caption:"دعاء بعد الصلاة",page:"17",url:"",level:"1",children:[]},
{caption:"دعاء الخروج من البيت",page:"19",url:"",level:"1",children:[]},
{caption:"دعاء المشي إلى المسجد",page:"20",url:"",level:"1",children:[]},
{caption:"دعاء دخول المسجد",page:"22",url:"",level:"1",children:[]},
{caption:"دعاء الخروج من المسجد",page:"23",url:"",level:"1",children:[]},
{caption:"دعاء ابتداء الطعام",page:"23",url:"",level:"1",children:[]},
{caption:"دعاء عند الفراغ من الأكل",page:"24",url:"",level:"1",children:[]},
{caption:"دعاء عند ابتداء الشرب",page:"25",url:"",level:"1",children:[]},
{caption:"دعاء عند الفراغ من الشرب",page:"25",url:"",level:"1",children:[]},
{caption:"دعاء النوم",page:"25",url:"",level:"1",children:[]},
{caption:"دعاء عند الاستيقاظ من النوم",page:"27",url:"",level:"1",children:[]},
{caption:"دعاء دخول المنزل",page:"27",url:"",level:"1",children:[]},
{caption:"دعاء ما بعد الأذان",page:"29",url:"",level:"1",children:[]},
{caption:"دعاء القيام من المجلس",page:"30",url:"",level:"1",children:[]},
{caption:"دعاء عند دخول الخلاء",page:"31",url:"",level:"1",children:[]},
{caption:"دعاء عند الخروج من الخلاء",page:"32",url:"",level:"1",children:[]},
{caption:"دعاء لبس الثوب",page:"32",url:"",level:"1",children:[]},
{caption:"دعاء لتقوية الحافظة",page:"33",url:"",level:"1",children:[]},
{caption:"دعاء ذكر السوق",page:"33",url:"",level:"1",children:[]},
{caption:"دعاء للحفظ من المعاصي",page:"34",url:"",level:"1",children:[]},
{caption:"نسب الرسول صلى الله عليه وآله وسلم",page:"35",url:"",level:"1",children:[]},
{caption:"ما يجب حفظه من الملائكة والكتب والرسل",page:"38",url:"",level:"1",children:[]},
{caption:"كيفية صلاة الجنازة",page:"40",url:"",level:"1",children:[]},
{caption:"الدعاء للميت بعد صلاة الجنازة",page:"40",url:"",level:"1",children:[]},
{caption:"أذكار الصباح والمساء",page:"44",url:"",level:"1",children:[]},
{caption:"تنبيه وفائدة",page:"53",url:"",level:"1",children:[]}
];