var ols=[
{caption:"الكلام وما يتألف منه",page:"1",url:"",level:"1",children:[]},
{caption:"باب الإعراب والبناء",page:"4",url:"",level:"1",children:[]},
{caption:"باب معرفة علامات الإعراب",page:"7",url:"",level:"1",children:[]},
{caption:"علامات الرفع",page:"7",url:"",level:"1",children:[]},
{caption:"علامات النصب",page:"9",url:"",level:"1",children:[]},
{caption:"علامات الخفض",page:"10",url:"",level:"1",children:[]},
{caption:"علامات الجزم",page:"12",url:"",level:"1",children:[]},
{caption:"فصل في أقسام المعربات",page:"13",url:"",level:"1",children:[]},
{caption:"الذي يعرب بالحركات",page:"13",url:"",level:"1",children:[]},
{caption:"الذي يعرب بالحروف",page:"13",url:"",level:"1",children:[]},
{caption:"تنبيه علم مما تقدم",page:"16",url:"",level:"1",children:[]},
{caption:"فصل في تقدير الحركات",page:"18",url:"",level:"1",children:[]},
{caption:"فصل في الاسم الذي لا ينصرف",page:"19",url:"",level:"1",children:[]},
{caption:"باب النكرة والمعرفة",page:"24",url:"",level:"1",children:[]},
{caption:"فصل في الضمير والمضمر",page:"26",url:"",level:"1",children:[]},
{caption:"فصل في العلم",page:"29",url:"",level:"1",children:[]},
{caption:"فصل في أسماء الإشارة",page:"31",url:"",level:"1",children:[]},
{caption:"فصل في الاسم الموصول",page:"33",url:"",level:"1",children:[]},
{caption:"فصل في المعرف بالأداة",page:"38",url:"",level:"1",children:[]},
{caption:"فصل في المضاف الى معرفة",page:"39",url:"",level:"1",children:[]},
{caption:"باب المرفوعات من الأسماء",page:"40",url:"",level:"1",children:[]},
{caption:"باب الفاعل",page:"41",url:"",level:"1",children:[]},
{caption:"باب نائب الفاعل المفعول الذي لم يسم فاعله",page:"45",url:"",level:"1",children:[]},
{caption:"باب المبتدأ والخبر",page:"48",url:"",level:"1",children:[]},
{caption:"باب العوامل التي تدخل على المبتدأ والخبر",page:"52",url:"",level:"1",children:[]},
{caption:"فصل كان وأخواتها",page:"53",url:"",level:"1",children:[]},
{caption:"فصل في الحروف المشبهة بليس",page:"56",url:"",level:"1",children:[]},
{caption:"فصل في أفعال المقاربة",page:"58",url:"",level:"1",children:[]},
{caption:"فصل النوع الثاني من النواسخ",page:"60",url:"",level:"1",children:[]},
{caption:"فصل في الكلام على لا العاملة عمل إن",page:"64",url:"",level:"1",children:[]},
{caption:"النوع الثالث من النواسخ",page:"67",url:"",level:"1",children:[]},
{caption:"باب المنصوبات من الأسماء",page:"72",url:"",level:"1",children:[]},
{caption:"باب المفعول به",page:"73",url:"",level:"1",children:[]},
{caption:"باب الاشتغال",page:"74",url:"",level:"1",children:[]},
{caption:"فصل في المنادى",page:"75",url:"",level:"1",children:[]},
{caption:"فصل في بيان المنادى المضاف إلى ياء المتكلم",page:"76",url:"",level:"1",children:[]},
{caption:"باب المفعول المطلق",page:"79",url:"",level:"1",children:[]},
{caption:"باب المفعول فيه",page:"81",url:"",level:"1",children:[]},
{caption:"باب المفعول من أجله",page:"83",url:"",level:"1",children:[]},
{caption:"باب المفعول معه",page:"84",url:"",level:"1",children:[]},
{caption:"فصل في المشبه بالمفعول",page:"84",url:"",level:"1",children:[]},
{caption:"باب الحال",page:"85",url:"",level:"1",children:[]},
{caption:"باب التمييز",page:"87",url:"",level:"1",children:[]},
{caption:"باب المستثنى",page:"89",url:"",level:"1",children:[]},
{caption:"باب المخفوضات من الأسماء",page:"93",url:"",level:"1",children:[]},
{caption:"فصل المخفوض بالإضافة",page:"96",url:"",level:"1",children:[]},
{caption:"باب إعراب الأفعال",page:"98",url:"",level:"1",children:[]},
{caption:"والنواصب",page:"99",url:"",level:"1",children:[]},
{caption:"والجوازم",page:"101",url:"",level:"1",children:[]},
{caption:"باب النعت",page:"105",url:"",level:"1",children:[]},
{caption:"باب العطف",page:"110",url:"",level:"1",children:[]},
{caption:"باب التوكيد",page:"114",url:"",level:"1",children:[]},
{caption:"باب البدل",page:"117",url:"",level:"1",children:[]},
{caption:"باب الأسماء العاملة عمل الفعل",page:"119",url:"",level:"1",children:[]},
{caption:"باب التنازع في العمل",page:"123",url:"",level:"1",children:[]},
{caption:"باب التعجب",page:"125",url:"",level:"1",children:[]},
{caption:"باب العدد",page:"126",url:"",level:"1",children:[]},
{caption:"باب الوقف",page:"129",url:"",level:"1",children:[]}
];