var ols=[
{caption:"التصريف الاصطلاحي",page:"1",url:"",level:"1",children:[]},
{caption:"الباب الأول من الثلاثي المجرد",page:"1",url:"",level:"1",children:[]},
{caption:"الباب الثاني من الثلاثي المجرد",page:"1",url:"",level:"1",children:[]},
{caption:"الباب الثالث من الثلاثي المجرد",page:"2",url:"",level:"1",children:[]},
{caption:"الباب الرابع من الثلاثي المجرد",page:"2",url:"",level:"1",children:[]},
{caption:"الباب الخامس من الثلاثي المجرد",page:"3",url:"",level:"1",children:[]},
{caption:"الباب السادس من الثلاثي المجرد",page:"4",url:"",level:"1",children:[]},
{caption:"باب الرباعي المجرد وهو باب واحد",page:"5",url:"",level:"1",children:[]},
{caption:"الباب الأول من الرباعي الملحق - وهو سبعة أبواب",page:"6",url:"",level:"1",children:[]},
{caption:"الباب الثاني من الرباعي الملحق",page:"6",url:"",level:"1",children:[]},
{caption:"الباب الثالث من الرباعي الملحق",page:"6",url:"",level:"1",children:[]},
{caption:"الباب الرابع من الرباعي الملحق",page:"6",url:"",level:"1",children:[]},
{caption:"الباب الخامس من الرباعي الملحق",page:"6",url:"",level:"1",children:[]},
{caption:"الباب السادس من الرباعي الملحق",page:"7",url:"",level:"1",children:[]},
{caption:"الباب السابع من الرباعي الملحق",page:"7",url:"",level:"1",children:[]},
{caption:"الباب الأول من الثلاثي المزيد",page:"7",url:"",level:"1",children:[]},
{caption:"التصريف اللغوي",page:"22",url:"",level:"1",children:[]},
{caption:"الفعل الماضي المبني للفاعل المتصل بضمير رفع",page:"22",url:"",level:"1",children:[]},
{caption:"الفعل الماضي المبني للمفعول المتصل بضمير رفع",page:"23",url:"",level:"1",children:[]},
{caption:"الفعل المضارع المبني للفاعل المتصل بضمير رفع",page:"24",url:"",level:"1",children:[]},
{caption:"الفعل المضارع المبني للمفعول المتصل بضمير رفع",page:"25",url:"",level:"1",children:[]},
{caption:"الفعل المضارع المبني للفاعل المتصل بنون التوكيد الثقيلة",page:"25",url:"",level:"1",children:[]},
{caption:"الفعل المضارع المبني للفاعل المتصل بنون التوكيد الخفيفة",page:"26",url:"",level:"1",children:[]},
{caption:"فعل الأمر المبني للفاعل للغائب والحاضر",page:"26",url:"",level:"1",children:[]},
{caption:"فعل الأمر المبني للمفعول",page:"27",url:"",level:"1",children:[]},
{caption:"فعل الأمر المؤكد بنون التوكيد الثقيلة",page:"27",url:"",level:"1",children:[]},
{caption:"فعل الأمر المبني للفاعل المؤكد بنون التوكيد الخفيفة",page:"28",url:"",level:"1",children:[]},
{caption:"فعل النهي المتصل بضمير رفع",page:"28",url:"",level:"1",children:[]},
{caption:"الضمير المنصوب المتصل بالفعل الماضي",page:"28",url:"",level:"1",children:[]},
{caption:"اسم الإشارة",page:"29",url:"",level:"1",children:[]},
{caption:"اسم الفاعل المرفوع",page:"29",url:"",level:"1",children:[]},
{caption:"اسم الفاعل المنصوب والمجرور",page:"30",url:"",level:"1",children:[]},
{caption:"اسم المفعول المرفوع",page:"30",url:"",level:"1",children:[]},
{caption:"اسم المفعول المنصوب والمجرور",page:"31",url:"",level:"1",children:[]},
{caption:"الصفة المشبهة المرفوعة",page:"31",url:"",level:"1",children:[]},
{caption:"أسماء الزمان والمكان والآلة",page:"31",url:"",level:"1",children:[]},
{caption:"مهمة",page:"32",url:"",level:"1",children:[]},
{caption:"تذييل",page:"33",url:"",level:"1",children:[]}
];