var ols=[
{caption:"مقدمة",page:"1",url:"",level:"1",children:[]},
{caption:"فصل أركان الإسلام",page:"2",url:"",level:"1",children:[]},
{caption:"فصل أركان الإيمان",page:"2",url:"",level:"1",children:[]},
{caption:"فصل معنى لاإله إلّا الله",page:"3",url:"",level:"1",children:[]},
{caption:"فصل علامات البلوغ",page:"3",url:"",level:"1",children:[]},
{caption:"فصل شروط إجزاء الحجر ",page:"3",url:"",level:"1",children:[]},
{caption:"فصل فروض الوضوء",page:"4",url:"",level:"1",children:[]},
{caption:"فصل النية ",page:"5",url:"",level:"1",children:[]},
{caption:"فصل الماء",page:"5",url:"",level:"1",children:[]},
{caption:"فصل موجبات الغسل",page:"6",url:"",level:"1",children:[]},
{caption:"فصل فروض الغسل",page:"6",url:"",level:"1",children:[]},
{caption:"فصل شرائط الوضوء",page:"7",url:"",level:"1",children:[]},
{caption:"فصل نواقض الوضوء",page:"8",url:"",level:"1",children:[]},
{caption:"فصل من انتقض وضوءه",page:"9",url:"",level:"1",children:[]},
{caption:"فصل أسباب التيمم",page:"10",url:"",level:"1",children:[]},
{caption:"فصل شروط التيمم",page:"11",url:"",level:"1",children:[]},
{caption:"فصل فروض التيمم",page:"12",url:"",level:"1",children:[]},
{caption:"فصل مبطلات التيمم",page:"12",url:"",level:"1",children:[]},
{caption:"فصل الّذي يطهر من النجاسات",page:"13",url:"",level:"1",children:[]},
{caption:"فصل النجاسات ثلاث",page:"13",url:"",level:"1",children:[]},
{caption:"فصل المغلّظة",page:"14",url:"",level:"1",children:[]},
{caption:"فصل أقلّ الحيض ",page:"15",url:"",level:"1",children:[]},
{caption:"فصل أعذار الصلاة",page:"16",url:"",level:"1",children:[]},
{caption:"فصل شروط الصلاة",page:"16",url:"",level:"1",children:[]},
{caption:"فصل أركان الصلاة",page:"18",url:"",level:"1",children:[]},
{caption:"فصل النية  ثلاث درجات",page:"20",url:"",level:"1",children:[]},
{caption:"فصل شروط تكبيرة الإحرام",page:"21",url:"",level:"1",children:[]},
{caption:"فصل شروط الفاتحة",page:"22",url:"",level:"1",children:[]},
{caption:"فصل تشديدات الفاتحة",page:"23",url:"",level:"1",children:[]},
{caption:"فصل يسنّ رفع اليدين",page:"25",url:"",level:"1",children:[]},
{caption:"فصل شروط السجود",page:"25",url:"",level:"1",children:[]},
{caption:"خاتمة أعضاء السجود",page:"26",url:"",level:"1",children:[]},
{caption:"فصل تشديدات التشهد",page:"26",url:"",level:"1",children:[]},
{caption:"فصل تشديدات أقلّ الصلاة على النبي",page:"28",url:"",level:"1",children:[]},
{caption:"فصل أقل السلام",page:"28",url:"",level:"1",children:[]},
{caption:"فصل أوقات الصلاة",page:"28",url:"",level:"1",children:[]},
{caption:"فصل تحرم الصلاة الّتي ليس لها سبب متقدم",page:"30",url:"",level:"1",children:[]},
{caption:"فصل سكتات الصلاة",page:"31",url:"",level:"1",children:[]},
{caption:"فصل الأركان التي تلزم فيها الطمأنينة",page:"32",url:"",level:"1",children:[]},
{caption:"فصل أسباب سجود السهو",page:"32",url:"",level:"1",children:[]},
{caption:"فصل أبعاض الصلاة",page:"33",url:"",level:"1",children:[]},
{caption:"فصل تبطل الصلاة",page:"34",url:"",level:"1",children:[]},
{caption:"فصل الّذي يلزم فيه نية الإمامة",page:"36",url:"",level:"1",children:[]},
{caption:"فصل شروط القدوة",page:"36",url:"",level:"1",children:[]},
{caption:"فصل صورة القدوة",page:"37",url:"",level:"1",children:[]},
{caption:"فصل شروط جمع التقديم",page:"38",url:"",level:"1",children:[]},
{caption:"فصل شروط جمع التأخير",page:"38",url:"",level:"1",children:[]},
{caption:"فصل شروط القصر",page:"39",url:"",level:"1",children:[]},
{caption:"فصل شروط الجمعة",page:"39",url:"",level:"1",children:[]},
{caption:"فصل أركان الخطبتين",page:"40",url:"",level:"1",children:[]},
{caption:"فصل شروط الخطبتين",page:"41",url:"",level:"1",children:[]},
{caption:"فصل الّذي يلزم للميت",page:"42",url:"",level:"1",children:[]},
{caption:"فصل أقلّ الغسل",page:"42",url:"",level:"1",children:[]},
{caption:"فصل أقلّ الكفن",page:"43",url:"",level:"1",children:[]},
{caption:"فصل أركان صلاة الجنازة",page:"43",url:"",level:"1",children:[]},
{caption:"فصل أقلّ الدّفن",page:"44",url:"",level:"1",children:[]},
{caption:"فصل ينبش الميت لأربع خصال",page:"45",url:"",level:"1",children:[]},
{caption:"فصل الاستعانات أربع خصال",page:"45",url:"",level:"1",children:[]},
{caption:"فصل الأموال الّتي تلزم فيها الزكاة",page:"46",url:"",level:"1",children:[]},
{caption:"فصل يجب صوم رمضان",page:"47",url:"",level:"1",children:[]},
{caption:"فصل شروط صحته",page:"48",url:"",level:"1",children:[]},
{caption:"فصل شروط وجوبه",page:"48",url:"",level:"1",children:[]},
{caption:"فصل أركانه ثلاثة أشياء",page:"49",url:"",level:"1",children:[]},
{caption:"فصل يجب مع القضاء للصوم الكفارة",page:"49",url:"",level:"1",children:[]},
{caption:"فصل يبطل الصوم",page:"51",url:"",level:"1",children:[]},
{caption:"فصل الإفطار في رمضان",page:"51",url:"",level:"1",children:[]},
{caption:"فصل الّذي لايفطر مما يصل إلى الجوف",page:"53",url:"",level:"1",children:[]}
];