var ols=[
{caption:"(Vol. 1) الجزء الأول",page:"1",url:"",level:"1",children:[]},
{caption:"(Vol. 2) الجزء الثاني",page:"24",url:"",level:"1",children:[]},
{caption:"المقدمة",page:"24",url:"",level:"1",children:[]},
{caption:"أحكام الإسلام",page:"26",url:"",level:"1",children:[]},
{caption:"الطهارة",page:"30",url:"",level:"1",children:[]},
{caption:"النّجاسات",page:"33",url:"",level:"1",children:[]},
{caption:"الإستنجاء",page:"35",url:"",level:"1",children:[]},
{caption:"فروض الوضوء",page:"36",url:"",level:"1",children:[]},
{caption:"الغسل",page:"41",url:"",level:"1",children:[]},
{caption:"التّيمم",page:"45",url:"",level:"1",children:[]},
{caption:"الصلاة",page:"48",url:"",level:"1",children:[]},
{caption:"صلاة الجماعة",page:"59",url:"",level:"1",children:[]},
{caption:"صلاة المسافر",page:"62",url:"",level:"1",children:[]},
{caption:"صلاة الجمعة",page:"63",url:"",level:"1",children:[]},
{caption:"صلاة الجنازة",page:"65",url:"",level:"1",children:[]},
{caption:"الزّكاة",page:"69",url:"",level:"1",children:[]},
{caption:"زكاة الفطر",page:"75",url:"",level:"1",children:[]},
{caption:"الصوم",page:"77",url:"",level:"1",children:[]},
{caption:"الحجّ",page:"80",url:"",level:"1",children:[]},
{caption:"(Vol. 3) الجزء الثالث",page:"84",url:"",level:"1",children:[]},
{caption:"المقدمة",page:"84",url:"",level:"1",children:[]},
{caption:"أصول الإسلام",page:"86",url:"",level:"1",children:[]},
{caption:"أحكام الإسلام",page:"88",url:"",level:"1",children:[]},
{caption:"الطهارة",page:"90",url:"",level:"1",children:[]},
{caption:"النّجاسات",page:"94",url:"",level:"1",children:[]},
{caption:"الإستنجاء",page:"97",url:"",level:"1",children:[]},
{caption:"الوضوء",page:"100",url:"",level:"1",children:[]},
{caption:"الغسل",page:"103",url:"",level:"1",children:[]},
{caption:"التّيمم",page:"105",url:"",level:"1",children:[]},
{caption:"الحيض والنّفاس",page:"107",url:"",level:"1",children:[]},
{caption:"الصّلاة",page:"110",url:"",level:"1",children:[]},
{caption:"أركان الصّلاة",page:"113",url:"",level:"1",children:[]},
{caption:"سنن الصّلاة",page:"116",url:"",level:"1",children:[]},
{caption:"مبطلات الصّلاة ومكروهاتها",page:"119",url:"",level:"1",children:[]},
{caption:"النوافل",page:"120",url:"",level:"1",children:[]},
{caption:"صلاة الجماعة",page:"122",url:"",level:"1",children:[]},
{caption:"أحوال المأموم",page:"124",url:"",level:"1",children:[]},
{caption:"صلاة المسافر",page:"127",url:"",level:"1",children:[]},
{caption:"صلاة الجمعة",page:"129",url:"",level:"1",children:[]},
{caption:"صلاة العيدين",page:"132",url:"",level:"1",children:[]},
{caption:"صلاة الجنازة",page:"134",url:"",level:"1",children:[]},
{caption:"الزّكاة",page:"137",url:"",level:"1",children:[]},
{caption:"زكاة الفطر",page:"140",url:"",level:"1",children:[]},
{caption:"الصوم",page:"142",url:"",level:"1",children:[]},
{caption:"الحجّ والعمرة",page:"145",url:"",level:"1",children:[]},
{caption:"شروط الطّواف والسّعي",page:"149",url:"",level:"1",children:[]},
{caption:"(Vol. 4) الجزء الرابع",page:"151",url:"",level:"1",children:[]},
{caption:"المقدمة",page:"151",url:"",level:"1",children:[]},
{caption:"الطهارة",page:"154",url:"",level:"1",children:[]},
{caption:"الوضوء",page:"161",url:"",level:"1",children:[]},
{caption:"المسح على الخفّين",page:"166",url:"",level:"1",children:[]},
{caption:"الغسل",page:"169",url:"",level:"1",children:[]},
{caption:"التيمّم",page:"171",url:"",level:"1",children:[]},
{caption:"دماء المرأة",page:"174",url:"",level:"1",children:[]},
{caption:"المحرّمات بالحدثين",page:"176",url:"",level:"1",children:[]},
{caption:"الصلاة",page:"179",url:"",level:"1",children:[]},
{caption:"صلاة المسافر",page:"189",url:"",level:"1",children:[]},
{caption:"صلاة الجمعة",page:"191",url:"",level:"1",children:[]},
{caption:"صلاة الجنازة",page:"194",url:"",level:"1",children:[]},
{caption:"الزكاة",page:"198",url:"",level:"1",children:[]},
{caption:"الصوم",page:"202",url:"",level:"1",children:[]},
{caption:"الحجّ",page:"206",url:"",level:"1",children:[]},
{caption:"الأضحيّة",page:"213",url:"",level:"1",children:[]},
{caption:"ما يحلّ أكله وما لايحلّ",page:"215",url:"",level:"1",children:[]},
{caption:"ما يحلّ من الصّيد والذّبائح وما يحرم",page:"218",url:"",level:"1",children:[]},
{caption:"البيوع",page:"220",url:"",level:"1",children:[]},
{caption:"الرّبا",page:"224",url:"",level:"1",children:[]},
{caption:"النّكاح",page:"227",url:"",level:"1",children:[]},
{caption:"الطّلاق",page:"234",url:"",level:"1",children:[]},
{caption:"الميراث",page:"240",url:"",level:"1",children:[]},
{caption:"الخاتمة",page:"247",url:"",level:"1",children:[]}
];